name: One-Tap Finalize Monorepo
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure git user
        run: |
          git config user.name "autoenroll-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Ensure target folders exist
        run: |
          mkdir -p apps/orchestrator/_imported
          mkdir -p docs
          mkdir -p .github/workflows

      - name: Write package.json (apps/orchestrator/_imported)
        run: |
          cat > apps/orchestrator/_imported/package.json <<'JSON'
          {
            "name": "autoenroll-orchestrator",
            "private": true,
            "version": "0.0.1",
            "scripts": {
              "start": "node server.js"
            }
          }
          JSON

      - name: Overwrite run_all.sh with path-safe version
        run: |
          cat > apps/orchestrator/_imported/run_all.sh <<'BASH'
          #!/usr/bin/env bash
          set -euo pipefail
          DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          echo "==> Bootstrapping in $DIR"
          if [ ! -f "$DIR/server.js" ]; then
          cat > "$DIR/server.js" <<'JS'
          const http=require('http');
          function serve(p,n){
            http.createServer((_,res)=>{
              res.writeHead(200,{'Content-Type':'text/plain'});
              res.end(`${n} up on ${p}\n`);
            }).listen(p,'0.0.0.0',()=>console.log(`[OK] ${n} on ${p}`));
          }
          serve(3000,'Portal'); serve(4000,'API'); serve(5055,'NAERSA mock');
          process.on('SIGINT',()=>process.exit(0));
          JS
          fi
          node "$DIR/server.js"
          BASH
          chmod +x apps/orchestrator/_imported/run_all.sh

      - name: Remove placeholder .keep if present
        run: |
          [ -f apps/orchestrator/_imported/.keep ] && git rm -f apps/orchestrator/_imported/.keep || true

      - name: Ensure Production Readiness doc exists
        run: |
          if [ ! -f docs/production-readiness.md ]; then
            printf "# Production Readiness Pack\n(placeholder – fill from ChatGPT canvas)\n" > docs/production-readiness.md
          fi

      - name: Drop minimal CI (green check)
        run: |
          cat > .github/workflows/ci.yml <<'YAML'
          name: CI
          on: [push, pull_request]
          jobs:
            boot:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                - uses: actions/setup-node@v4
                  with: { node-version: '20' }
                - name: Start server
                  run: |
                    node apps/orchestrator/_imported/server.js &
                    sleep 1
                - name: Check health
                  run: curl -sSf http://localhost:3000
          YAML

      - name: Commit & push changes
        run: |
          git add -A
          git commit -m "chore: one-tap finalize — pkg, safe run_all.sh, docs, CI" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
